language: java
jdk:
  - openjdk17

branches:
  only:
    - main

#gradle lib cache
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

#git master push after code
script: "./gradlew clean build"

#notice to my mail
notifications:
  email:
    recipients:
      - 'mallangyi@naver.com'